{{ range .Values.domains -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/limit-rps: "10"
    nginx.ingress.kubernetes.io/rewrite-target: "/$1"
    nginx.ingress.kubernetes.io/upstream-vhost: "{{ .origin }}"
    cert-manager.io/cluster-issuer: letsencrypt
  name: {{ include "reverse-proxy.name" . }}
spec:
  tls:
  - hosts:
      - {{ .origin }}
    secretName: {{ include "reverse-proxy.tlsName" . }}
  rules:
  - host: {{ .origin }}
    http:
      paths:
      - backend:
          service:
            name: {{ include "reverse-proxy.name" . }}
            port:
              number: 80
        path: /(.*)
        pathType: Prefix
---
{{ end -}}
