version: 2

jobs:
  integrationTests:
    docker:
      - image: web3f/ci-commons:v2.4.8
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          description: run integration tests
          command: |
            /scripts/integration-tests.sh
  helmLint:
    docker:
      - image: web3f/ci-commons:v2.4.8
    steps:
      - checkout
      - run:
          command: |
            helm lint ./charts/reverse-proxy

  publishChart:
    docker:
      - image: web3f/ci-commons:v2.4.8
    steps:
      - checkout
      - run:
          command: |
            /scripts/publish-chart.sh

  deploy:
    docker:
      - image: web3f/ci-commons:v2.4.8
    steps:
      - checkout
      - run:
          command: |
            ./scripts/deploy.sh

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - helmLint:
          filters:
            tags:
              only: /.*/
      - integrationTests:
          filters:
            tags:
              only: /.*/
      - publishChart:
          context: github-bot
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
          requires:
            - integrationTests
            - helmLint

      - deploy:
          context: digital_ocean_access
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
          requires:
            - publishChart
